### ISSUE TITLE
How to use signals for a template?

### ISSUE THREAD

**Issue by sonus21** [Wtower/django-ninecms#61]
Let say we have created signal `get_all_items` from admin and  have added required page types e.g. `items`.

How to use signal `get_all_items` in `items.html`. I tried following steps.

According to docs 
1. Create an app XYZ
2. Add XYZ to settings.py
3. Add an file `signals.py` and define some function 
4. I have defined 

``` python
from django import dispatch
from ninecms.signals import block_signal

@dispatch.receiver(block_signal)
def get_all_items(**kwargs):
    print("I am called")
```

This function is not being invoked, if it invokes then what should be the context variable name and how it should be returned?

Even I tried by adding a custom block name `get_all_items` in items.html.

What should be the correct way to use it?

**Comment by Wtower** [comment]
Fair question, the documentation lacks an example. The signal is called at the moment that a page is rendered, and can return any Python object, usually some queryset. This can then be accessed in the template using a context variable that has the same name with the block name in content (admin).

For example, if there is a content block in admin with the name `all_items` that is of type signal, and the signal name is `view_all_items`, then when the page is rendered a signal function can be:

```
from django import dispatch
from django.db.models import Q
from ninecms import signals


@dispatch.receiver(signals.block_signal)
def render_view(**kwargs):
    if kwargs['view'] == 'view_all_items':
        nodes = Node.objects\
            .filter(page_type__name='X')\
            .filter(status=True)\
            .filter(Q(language=kwargs['request'].LANGUAGE_CODE) | Q(language=''))\
            .prefetch_related('image_set')\
            .order_by('-sticky', '-promote', '?')
        return nodes[:4]
```

This can be accessed in template with `{{ all_items }}`.

Documentation and example project will be updated in next version accordingly.

Please do not hesitate to ask if you have other questions.

**Comment by Wtower** [comment]
Relevant section to update in documentation:

https://github.com/Wtower/django-ninecms/blob/v0.6.0/README.rst#views

**Comment by sonus21** [comment]
It doesn't seem to be working for me. Function is still not being invoked. Can you test on a custom project  and update on github as startup project.

**Comment by Wtower** [comment]
I suspect that this has to do with Django signals in general and not this specific feature.

In general, I would recommend you to create a second app in your project, eg `myproject_core`, include it in your `INSTALLED_APPS`, and add the following files:

First a `myproject_core/signals.py` as mentioned above.

Second, a `myproject_core/apps.py`:

```
from django.apps import AppConfig


class MyprojectCoreConfig(AppConfig):
    name = 'myproject_core'
    verbose_name = "My Project"

    def ready(self):
        import myproject_core.signals
```

Last, a `myproject_core/__init__.py`:

```
default_app_config = 'myproject_core.apps.MyprojectCoreConfig'
```

http://www.koopman.me/2015/01/django-signals-example/

**Comment by sonus21** [comment]
Thanks. 2nd method is working perfectly. Please update doc.
